# Default values for nginx
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Common controls
environment: dev
application: nginx
containerPort: 8080

# Service controls
service:
  name: nginx-svc
  type: ClusterIP
  port: 8080

# Route controls
route:
  name: nginx-route
  hostName: nginx-ibtech-demo.apps.ocp.dataserv.local

# Deployment controls
restartPolicy: Always
replicas: 1
resources:
  requests:
    cpu: 150m
    memory: 500Mi
  limits:
    cpu: 500m
    memory: 1Gi

image:
  imagePullPolicy: Always
  dev:
    repository: image-registry.openshift-image-registry.svc:5000/ibtech-devops/nginx-hello-world
    tag: latest
  test:
    repository: quay.io/swoturkey/nginx
    tag: QAlatest
  preprod:
    repository: quay.io/swoturkey/nginx
    tag: preplatest
  prod:
    repository: quay.io/swoturkey/nginx
    tag: latest

# ConfigMap-Secret controls
index_text: IBTech Core Services
version_number: 1.1.0
dev:
  secret_env: devValue
test:
  secret_env: testValue
preprod:
  secret_env: preprodValue
prod:
  secret_env: prodValue
