apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-{{ .Values.application }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
data:
  index.html: |+
    <html>
    <body>
      <h1>Hello, world from nginx to {{ .Values.index_text }} {{ .Values.version_number }}!</h1>
    </body>
    </html>