apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.application }}-{{ .Values.environment }}
  name: {{ .Values.application }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.application }}-{{ .Values.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.application }}-{{ .Values.environment }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
      - name: {{ .Values.application }}
        {{ if eq .Values.environment "dev" }}
        image: {{ .Values.image.dev.repository }}:{{ .Values.image.dev.tag }}
        {{ else if eq .Values.environment "test" }}
        image: {{ .Values.image.test.repository }}:{{ .Values.image.test.tag }}
        {{ else if eq .Values.environment "preprod" }}
        image: {{ .Values.image.preprod.repository }}:{{ .Values.image.preprod.tag }}
        {{ else if eq .Values.environment "prod" }}
        image: {{ .Values.image.prod.repository }}:{{ .Values.image.prod.tag }}
        {{ end }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        ports:
          - containerPort: {{ .Values.containerPort }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: "{{ .Values.resources.requests.memory }}"
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: "{{ .Values.resources.limits.memory }}"
        env:
        - name: secretEnv
          valueFrom:
            secretKeyRef:
              name: sec-{{ .Values.application }}-{{ .Values.environment }}
              key: secret-env
        volumeMounts:
        - name: index
          mountPath: /usr/share/nginx/html/
          readOnly: false
      volumes:
      - name: index
        configMap:
          name: cm-{{ .Values.application }}-{{ .Values.environment }}
          defaultMode: 0755