apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.application }}
  name: {{ .Values.route.name }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.route.hostName }}
  port:
    targetPort: {{ .Values.service.port }}
  path: "/"
  to:
    kind: Service
    name: {{ .Values.service.name }}-{{ .Values.environment }}
    weight: 100
  wildcardPolicy: None