apiVersion: v1
kind: Secret
metadata:
  name: sec-{{ .Values.application }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ if eq .Values.environment "dev" }}
  secret-env: {{ .Values.dev.secret_env }}
  {{ else if eq .Values.environment "test" }}
  secret-env: {{ .Values.test.secret_env }}
  {{ else if eq .Values.environment "preprod" }}
  secret-env: {{ .Values.preprod.secret_env }}
  {{ else if eq .Values.environment "prod" }}
  secret-env: {{ .Values.prod.secret_env }}
  {{ end }}